"""empty message

Revision ID: 7bc90a31f4c8
Revises: 
Create Date: 2021-01-16 03:09:49.587776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc90a31f4c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('names', sa.String(), nullable=False))
    op.drop_column('actor', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('actor', 'names')
    # ### end Alembic commands ###
